name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} > ~/.ssh/known_hosts

      - name: Connect and pull
        run: |
           ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
            set -e

            mkdir -p $HOME/projects

            if [ ! -d '${{ github.event.repository.name }}' ]; then
              git clone git@github.com:${{ github.repository }}.git
            fi

            cd $HOME/projects/${{ github.event.repository.name }}
            git checkout main
            git pull

            docker compose down
            docker compose up --build -d
          "
      - name: Clean up
        run: rm -rf ~/.ssh

