name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install registered SSH keys to githubs Ubuntu machine
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} > ~/.ssh/known_hosts

      - name: Connect to VPS, pull changes and deploy to docker
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} '
            set -e

            if [ ! -d '$HOME/projects/${{ github.repository_owner }}/${{ github.event.repository.name }}']
              mkdir -p $HOME/projects/${{ github.repository_owner }}
              git clone git@github.com:${{ github.repository_owner }}/${{ github.event.repository.name }}.git
              cd $HOME/projects/${{ github.repository_owner }}/${{ github.event.repository.name }}
            else
              cd $HOME/projects/${{ github.repository_owner }}/${{ github.event.repository.name }}
              git pull
            fi

            docker compose down
            docker compose up --build -d
          '

      - name: Clean up
        run: rm -rf ~/.ssh

